import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/components/auth/AuthProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {/* global auth header */}
          {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
          <div>
            {/* AuthHeader is client component showing user and sign out */}
            {/* Import inline to avoid server/client mismatch in layout */}
            {/* ...rendered inside AuthProvider*/}
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
